devices: Pixel 6|gs101-oriole
Pixel6 is a new device in LKFT, this brings in the config changes.
These changes require a newer version of mkbootimg because this is broken
currently upstream. I have included the mkbootimg script that excludes
the gki calls that was breaking it.

> docker run -ti ubuntu bash
root@9a86bcf4df6e:/# apt update && apt install mkbootimg
root@9a86bcf4df6e:/# mkbootimg
Traceback (most recent call last):
  File "/usr/bin/mkbootimg", line 31, in <module>
    from gki.generate_gki_certificate import generate_gki_certificate
ModuleNotFoundError: No module named 'gki'

Co-developed-by: Anders Roxell <anders.roxell@linaro.org>
Signed-off-by: Benjamin Copeland <ben.copeland@linaro.org>